### ISSUE TITLE
windows compilation:__cdecl and __stdcall attributes mismatch

### ISSUE THREAD

**Issue by AlexanderZvyagin** [numericalalgorithmsgroup/nagcpp#2]
I am getting the following compilation error with on 'ex_c05ay.cpp' example (windows, msvc, 32-bits NAG).

cannot convert
'void (__cdecl *)(const std::function<double(const nagcpp::data_handling::CallbackAddresses *, ...)>
to
'void (__stdcall *)(const std::function<double(const nagcpp::data_handling::CallbackAddresses *, ...)>

What is the best way to fix this?
Thanks!

**Comment by davidcarlisle** [comment]
@AlexanderZvyagin  Thanks for your query. Could you please submit it via email to
[support@nag.co.uk](mailto:support@nag.co.uk)
and to report any further issues/questions to that email address so that they can be tracked by our support service, thanks.

**Comment by davidcarlisle** [comment]
@AlexanderZvyagin  actually I forwarded it to support already, so they should be in touch, you don't need to resend.
